### ISSUE TITLE
Fluidification de la détection d'angle

### ISSUE THREAD

**Issue by narduzzi** [Fasjul/Projet_GroupeAD#14]
Optimisation de la reconnaissance de mouvements de la planche : 
- suppression de "bruit/tremblements"

**Comment by robinweiskopf** [comment]
Je ne sais pas si on peut faire grand chose, c'est un problème de webcam ça.

**Comment by narduzzi** [comment]
Ya moyen p-e de supprimer les "bruits" de webcam qui créent des petites variations ou des grandes variations (genre des rotations <1° de >=60° en une frame). Je vais me pencher sur le problème.

**Comment by narduzzi** [comment]
Plus ou moins amélioré. Il n'y a plus de "grand sauts".
C'est surtout dépendant de la caméra je crois.
