### ISSUE TITLE
Blob detection algorithm

### ISSUE THREAD

**Issue by narduzzi** [Fasjul/Projet_GroupeAD#16]
Implement the "Blob detection" algorithm

**Comment by narduzzi** [comment]
@robinweiskopf Ca donne quoi?

**Comment by robinweiskopf** [comment]
Ah euh j'ai oublié de fermer l'issue, l'algorithme fonctionne ! Le seul truc que je comprends pas trop c'est qu'en fait il prend _TOUS_ les blobs, donc si y'a 1 pixel sur l'image qui diffère, il va le considérer comme blobl.

**Comment by narduzzi** [comment]
Comment ca? Il est sensé faire un filtre par rapport à la couleur, et ensuite l'algorithme doit runner sur une image filtrée (noir et blanc seulement).

Du coup, il run une fois sur l'image binaire, et la labelle.
Au deuxième passage, les labels sont regroupés par équivalence, et ca nous donne le nombre de blob.

**Comment by robinweiskopf** [comment]
Oui, mais si l'image est très brouillée il risque de détecter des milliers de blobs.

**Comment by narduzzi** [comment]
Je pense que ça fait partie des désavantages de l'algorithme. Tout ce qu'on peut faire pour éviter ça c'est éventuellement flouter légèrement l'image binaire.

**Comment by narduzzi** [comment]
@robinweiskopf ? C'est OK?

**Comment by robinweiskopf** [comment]
Not fixed for final submission.
