### ISSUE TITLE
La balle ne rebondit pas

### ISSUE THREAD

**Issue by narduzzi** [Fasjul/Projet_GroupeAD#18]
La balle ne rebondit pas comme avant! Elle reste collée au cylindre!

**Comment by robinweiskopf** [comment]
Je vois ça, dès que je place un cylindre, la balle se colle contre!

**Comment by robinweiskopf** [comment]
Cela marche à présent non?

**Comment by narduzzi** [comment]
Oui! Problème reglé avec le commit d47d79a4aad9531d470695f4f38245043addbf41
