### ISSUE TITLE
Régler les rotations en fonction de l'orientation de la planche.

### ISSUE THREAD

**Issue by narduzzi** [Fasjul/Projet_GroupeAD#19]
J'ai pas la planche lego, du coup c'est difficile de régler l'orientation des rotations (rotation x en miroir genre).

Tu pourrais essayer de vérifier que les rotations sont correctes ?

**Comment by robinweiskopf** [comment]
Réglé avec d510a97aa5ff2ad986b84417c6621fffa51d0022
