### ISSUE TITLE
Rendre le code concurrent

### ISSUE THREAD

**Issue by narduzzi** [Fasjul/Projet_GroupeAD#8]
Il faudrait qu'on rende la méthode Sobel et une partie de la méthode Hough concurrentes pour que l'image rendue à la Webcam soit plus fluide

**Comment by robinweiskopf** [comment]
Ca joue, je m'occupe de cette partie !

**Comment by narduzzi** [comment]
Okay! Mais je m'occupe de faire la partie de Hough concurrente. Comme ca je bosse direct sur l'algo de reconnaissance de egde.

**Comment by narduzzi** [comment]
Alors je vais m'occuper de rendre le dessin des lignes parallèle.
Y'a pas un problème avec le Sobel? Il me semble qu'il y a beaucoup plus de bruit qu'avant. Ca fait qu'il y a beaucoup trop de accuVal>200 et ca crée la dose de lignes..

**Comment by robinweiskopf** [comment]
Oui, j'ai mis dans les notes du commit 087eb160cf432750638b750b3b79c9bff38d93c3 que Sobel marche bizarrement qu'avec un seul coeur et quand j'utilise les coeurs HT de mon Intel i7 ça donne des fautes...

**J'ai fait une méthode** `PImage applyAll(PImage)` **qui applique toutes les transformations pour que le résultat soit correct!**

**Comment by narduzzi** [comment]
Dessin des lignes bien plus rapide grâce au stockage des valeurs de sin et cos.
Découvrez dès maintenant les nouveaux TabCos et TabSin!
Commit : 81dd0eaafdfcb8fb902aee2c162770ef501189fa

**Comment by robinweiskopf** [comment]
Annulé la parallélisation, on obtient des bonnes performances de ~120ms en séquentiel avec des optimisations du code dans 7f08a7454e54210fb44958ea0f073d525b294aad .
